version: '3'
services:
  mysql:
    image: mysql:8.0.18
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データ
    environment:
      - "MYSQL_DATABASE=scala-sandbox"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    ports:
      - "3306:3306"
    
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
